server.port=8080
storage.nodes=${STORAGE_NODES:http://localhost:8081,http://localhost:8082}
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
health.check.interval.ms=10000
replication.factor=2
